name: Build release
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Compile native executables
        run: |
          mkdir target
          GOOS=darwin GOOARCH=amd64 go build -o target/cloudflare-ddns-darwin-amd64
          GOOS=darwin GOOARCH=arm64 go build -o target/cloudflare-ddns-darwin-arm64
          GOOS=linux GOARCH=amd64 go build -o target/cloudflare-ddns-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o target/cloudflare-ddns-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o target/cloudflare-ddns-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o target/cloudflare-ddns-windows-arm64.exe

      - name: Bump next version
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: --unreleased --bump -o current-version.md
        env:
          OUTPUT: current-version.md

      - name: Tag version
        run: |
          git tag "${{ steps.git-cliff.outputs.changelog }}"
          git push --tags

      - name: Update Changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --bump -o CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md

      - name: Push CHANGELOG.md changes
        run: |
          git add CHANGELOG.md
          git commit -m "update CHANGELOG.md"
          git push

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'target/*'
          bodyFile: 'current-version.md'
