name: Build release
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Compile native executables
        run: |
          mkdir target
          GOOS=darwin GOARCH=amd64 go build -o target/cloudflare-ddns-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o target/cloudflare-ddns-darwin-arm64
          GOOS=linux GOARCH=amd64 go build -o target/cloudflare-ddns-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o target/cloudflare-ddns-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o target/cloudflare-ddns-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o target/cloudflare-ddns-windows-arm64.exe

      - name: Tag version
        id: tag
        run: |
          export VERSION="$(date +%Y-%m-%d.%H%M%S)"
          git tag "$VERSION"
          git push --tags
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.version }}
          artifacts: 'target/*'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: magonx/cloudflare-ddns:${{ steps.tag.outputs.version }},magonx/cloudflare-ddns:latest
