name: Build release
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Compile native executables
        run: |
          mkdir target
          GOOS=darwin GOARCH=amd64 go build -o target/cloudflare-ddns-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o target/cloudflare-ddns-darwin-arm64
          GOOS=linux GOARCH=amd64 go build -o target/cloudflare-ddns-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o target/cloudflare-ddns-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o target/cloudflare-ddns-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o target/cloudflare-ddns-windows-arm64.exe

      - name: Tag version
        run: |
          git tag "$(date +%Y-%m-%d.%H%M%S)"
          git push --tags

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'target/*'
