name: Build release
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '*-alpha.*'
      - '*-beta.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --no-exec --github-repo ${{ github.repository }}
        env:
          OUTPUT: CHANGES.md

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile Jar
        run: ./gradlew build

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/libs/cloudflare-ddns.jar'
          bodyFile: 'CHANGES.md'
