name: Build release
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt install -y jq

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Compile native executables
        run: |
          mkdir target
          GOOS=darwin GOOARCH=amd64 go build -o target/cloudflare-ddns-darwin-amd64
          GOOS=darwin GOOARCH=arm64 go build -o target/cloudflare-ddns-darwin-arm64
          GOOS=linux GOARCH=amd64 go build -o target/cloudflare-ddns-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o target/cloudflare-ddns-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o target/cloudflare-ddns-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o target/cloudflare-ddns-windows-arm64.exe

      - name: Bump version
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --unreleased --bump --context --output context.json

      - name: Tag new version
        run: |
          export VERSION=$(cat context.json | jq '.[0].version' | tr -d '"')
          git tag "$VERSION"
          git push --tags

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --latest -o current-version.md

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'target/*'
          bodyFile: 'current-version.md'
